//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vaConnect.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("vaConnect.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;WLANProfile xmlns=&quot;http://www.microsoft.com/networking/WLAN/profile/v1&quot;&gt;
        ///  &lt;name&gt;fon_vmnac_int&lt;/name&gt;
        ///  &lt;SSIDConfig&gt;
        ///    &lt;SSID&gt;
        ///      &lt;hex&gt;666F6E5F766D6E61635F696E74&lt;/hex&gt;
        ///      &lt;name&gt;fon_vmnac_int&lt;/name&gt;
        ///    &lt;/SSID&gt;
        ///    &lt;nonBroadcast&gt;false&lt;/nonBroadcast&gt;
        ///  &lt;/SSIDConfig&gt;
        ///  &lt;connectionType&gt;ESS&lt;/connectionType&gt;
        ///  &lt;connectionMode&gt;auto&lt;/connectionMode&gt;
        ///  &lt;autoSwitch&gt;false&lt;/autoSwitch&gt;
        ///  &lt;MSM&gt;
        ///    &lt;security&gt;
        ///      &lt;authEncryption&gt;
        ///        &lt;authentication&gt;WPA2&lt;/authenticatio [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EapPEAP {
            get {
                return ResourceManager.GetString("EapPEAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt; 
        ///&lt;WLANProfile xmlns=&quot;http://www.microsoft.com/networking/WLAN/profile/v1&quot;&gt;
        ///    &lt;name&gt;SampleWPAEnterpriseTLS&lt;/name&gt;
        ///    &lt;SSIDConfig&gt;
        ///        &lt;SSID&gt;
        ///            &lt;name&gt;{0}&lt;/name&gt;
        ///        &lt;/SSID&gt;
        ///        &lt;nonBroadcast&gt;false&lt;/nonBroadcast&gt;
        ///    &lt;/SSIDConfig&gt;
        ///    &lt;connectionType&gt;ESS&lt;/connectionType&gt;
        ///    &lt;connectionMode&gt;auto&lt;/connectionMode&gt;
        ///    &lt;autoSwitch&gt;false&lt;/autoSwitch&gt;
        ///    &lt;MSM&gt;
        ///        &lt;security&gt;
        ///            &lt;authEncryption&gt;
        ///                &lt;authenticat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EapTLS {
            get {
                return ResourceManager.GetString("EapTLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;WLANProfile xmlns=&quot;http://www.microsoft.com/networking/WLAN/profile/v1&quot;&gt;
        ///	&lt;name&gt;fon_vmnac_int&lt;/name&gt;
        ///	&lt;SSIDConfig&gt;
        ///		&lt;SSID&gt;
        ///			&lt;hex&gt;666F6E5F766D6E61635F696E74&lt;/hex&gt;
        ///			&lt;name&gt;fon_vmnac_int&lt;/name&gt;
        ///		&lt;/SSID&gt;
        ///		&lt;nonBroadcast&gt;false&lt;/nonBroadcast&gt;
        ///	&lt;/SSIDConfig&gt;
        ///	&lt;connectionType&gt;ESS&lt;/connectionType&gt;
        ///	&lt;connectionMode&gt;auto&lt;/connectionMode&gt;
        ///	&lt;autoSwitch&gt;false&lt;/autoSwitch&gt;
        ///	&lt;MSM&gt;
        ///		&lt;security&gt;
        ///			&lt;authEncryption&gt;
        ///				&lt;authentication&gt;WPA2&lt;/authentication&gt;
        ///				&lt;encryption&gt;AES&lt;/enc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EapTTLSy {
            get {
                return ResourceManager.GetString("EapTTLSy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fon_logo {
            get {
                object obj = ResourceManager.GetObject("fon_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_launcher {
            get {
                object obj = ResourceManager.GetObject("ic_launcher", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap main_white {
            get {
                object obj = ResourceManager.GetObject("main_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://vmnac-int.fon.com.
        /// </summary>
        internal static string UriVAConnect {
            get {
                return ResourceManager.GetString("UriVAConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap vaconnect {
            get {
                object obj = ResourceManager.GetObject("vaconnect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap web_hi_res_512 {
            get {
                object obj = ResourceManager.GetObject("web_hi_res_512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
